# https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs
defaults: &defaults
  docker:
    - image: circleci/php:7.1-jessie-node-browsers-legacy
  working_directory: ~/example_wordpress_composer
  environment:
    #=========================================================================
    # In addition to the environment variables defined in this file, also
    # add the following variables in the Circle CI UI.
    #
    # See: https://circleci.com/docs/2.0/environment-variables/
    #
    # TERMINUS_SITE:  Name of the Pantheon site to run tests on, e.g. my_site
    # TERMINUS_TOKEN: The Pantheon machine token
    # GITHUB_TOKEN:   The GitHub personal access token
    # GIT_EMAIL:      The email address to use when making commits
    #
    # TEST_SITE_NAME: The name of the test site to provide when installing.
    # ADMIN_PASSWORD: The admin password to use when installing.
    # ADMIN_EMAIL:    The email address to give the admin when installing.
    #=========================================================================
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"

    # The variables below usually do not need to be modified.

    #======================================================================================================================================
    # Circle CI 2.0 does not yet expand environment variables so they have to be manually EXPORTed
    # Once environment variables can be expanded the variables below can be uncommented and the EXPORTs in set-up-globals.sh can be removed
    # See: https://discuss.circleci.com/t/unclear-how-to-work-with-user-variables-circleci-provided-env-variables/12810/11
    # See: https://discuss.circleci.com/t/environment-variable-expansion-in-working-directory/11322
    # See: https://discuss.circleci.com/t/circle-2-0-global-environment-variables/8681
    #======================================================================================================================================
    # See set-up-globals.sh for more environment variables

    NOTIFY: 'scripts/github/add-commit-comment {project} {sha} "Created multidev environment [{site}#{env}]({dashboard-url})." {site-url}'
    ADMIN_USERNAME: admin
    BUILD_TOOLS_VERSION: dev-master
    TERM: dumb

version: 2
jobs:
    # @todo: common initialization, maybe
    build:
        <<: *defaults
        steps:
            - checkout

            - restore_cache:
                keys:
                    - composer-cache
                    - terminus-install
                    - composer-sage

            - run:
                name: dependencies
                command: ./.circleci/set-up-globals.sh

            - run:
                name: install dev dependencies
                command: composer install --no-ansi --no-interaction --optimize-autoloader --no-progress

            - run:
                name: Install Sage Theme Composer Dependencies
                command: cd ./web/wp-content/themes/droper && composer install --no-ansi --no-interaction --optimize-autoloader --no-progress

            - run:
                name: Install Yarn
                command: cd ./web/wp-content/themes/droper && sudo npm install -g yarn

            - run:
                name: install theme dependencies
                command: cd ./web/wp-content/themes/droper && yarn && yarn build

            - save_cache:
                key: composer-cache
                paths:
                    - $HOME/.composer/cache

            - save_cache:
                key: composer-sage-theme
                paths:
                    - $HOME/web/wp-content/themes/droper/vendor

            - save_cache:
                key: terminus-install
                paths:
                    - $HOME/.terminus
                    - $HOME/terminus

            - persist_to_workspace:
                # Must be relative path from working_directory
                root: .
                # Must be relative path from root
                paths:
                    - vendor
                    - web/wp-content/themes/droper


    # code_sniff_unit_test:
    #     <<: *defaults
    #     steps:
    #         - checkout
    #
    #         - attach_workspace:
    #             # Must be absolute path or relative path from working_directory
    #             at: /tmp
    #
    #         - run:
    #             name: copy vendor/web
    #             command: cp -r /tmp/vendor .
    #
    #         - run:
    #             name: check for WordPress coding standards
    #             command: composer -n code-sniff
    #
    #         - run:
    #             name: run unit tests
    #             command: composer -n unit-test

    build_and_deploy:
        <<: *defaults
        steps:
            - checkout

            - restore_cache:
                keys:
                    - composer-cache
                    - terminus-install
                    - composer-sage-theme

            - run:
                name: dependencies
                command: ./.circleci/set-up-globals.sh

            - run:
                name: build assets
                command: composer -n build-assets

            - run:
                name: Install Sage Theme Composer Dependencies
                command: cd ./web/wp-content/themes/droper && composer install --no-ansi --no-interaction --optimize-autoloader --no-progress

            - run:
                name: Install Yarn
                command: cd ./web/wp-content/themes/droper && sudo npm install -g yarn

            - run:
                name: install theme dependencies
                command: cd ./web/wp-content/themes/droper && yarn && yarn build

            - store_artifacts:
                path: ./web/wp-content/themes/droper/dist

            - run:
                name: deploy to Pantheon
                command: ./.circleci/deploy-to-pantheon.sh

    behat_test:
        <<: *defaults
        steps:
            - checkout

            - attach_workspace:
                # Must be absolute path or relative path from working_directory
                at: /tmp

            - restore_cache:
                keys:
                    - terminus-install

            - run:
                name: copy vendor
                command: cp -r /tmp/vendor .

            - run:
                name: dependencies
                command: ./.circleci/set-up-globals.sh

            - run:
                name: run Behat tests
                command: ./.circleci/behat-test.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      # Install dev dependencies
      - build
      # Build and deploy
      - build_and_deploy
      # Code sniff and unit text first
      # - code_sniff_unit_test:
      #       requires:
      #           - build
      # Run Behat tests after deploy so they can be done on Pantheon
      - behat_test:
            requires:
                - build
                - build_and_deploy
